# Generated by Django 3.0.1 on 2020-01-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='new_task',
            field=models.BooleanField(default=True),
        ),
    ]
