# Generated by Django 3.0.1 on 2020-01-10 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_task_new_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='new_task',
        ),
    ]
